"""Wie klein KANN die Schaltung sein - und was ist beweisbar?"""
import math

N=65536; NV=16; k=81

print("="*72)
print("1) ABZAEHLSCHRANKE (Shannon-Argument) - das ist beweisbar")
print("="*72)
# Zahl der Funktionen mit genau k Mintermen aus N
log2_funktionen = (math.lgamma(N+1)-math.lgamma(k+1)-math.lgamma(N-k+1))/math.log(2)
print(f"  Funktionen mit genau {k} Mintermen aus {N}: 2^{log2_funktionen:.0f}")
print()
print("  Zahl der Schaltungen mit g Gattern ueber 16 Eingaengen:")
print("  jedes Gatter waehlt 2 Quellen aus (16+g) und eine von 16 Bool. Ops")
print(f"  -> ((16+g)^2 * 16)^g")
print()
print(f"  {'g':>6} {'log2(Schaltungen)':>20} {'reicht fuer 2^786?':>20}")
schwelle=None
for g in [10,20,30,40,45,49,50,60,100]:
    log2_c = g*math.log2((NV+g)**2 * 16)
    reicht = "ja" if log2_c>=log2_funktionen else "nein"
    if log2_c>=log2_funktionen and schwelle is None: schwelle=g
    print(f"  {g:>6} {log2_c:>20.0f} {reicht:>20}")
print()
print(f"  -> Erst ab ca. g = {schwelle} Gattern gibt es genug Schaltungen,")
print(f"     um alle 2^{log2_funktionen:.0f} solcher Funktionen darzustellen.")
print()
print(f"  BEWEISBARE AUSSAGE: FAST ALLE Funktionen mit {k} Mintermen brauchen")
print(f"  mindestens ~{schwelle} Gatter. Das ist ein echter Beweis - aber er gilt")
print(f"  fuer 'fast alle', nicht fuer UNSERE konkrete Funktion.")
print()
print("="*72)
print("2) DIE LUECKE - und was sie bedeutet")
print("="*72)
print(f"  Untere Schranke (Abzaehlung, gilt fuer fast alle):  ~{schwelle} Gatter")
print(f"  Obere Schranke (haben wir gebaut):                  747 Operationen")
print(f"  -> Faktor {747/schwelle:.0f} Luecke")
print()
print("  DAS IST DIE ENTSCHEIDENDE ZAHL FUER DEINE FRAGE 1:")
print("  Die Abzaehlung VERBIETET keine kleine Schaltung. Zwischen 49 und 747")
print("  ist jede Groesse informationstheoretisch moeglich. Wenn es eine")
print("  Schaltung mit 100 Gattern gibt, widerspricht das keinem bekannten Satz.")
print()
print("="*72)
print("3) WAS EXAKT BEWEISBAR IST: SAT-basierte exakte Synthese")
print("="*72)
print("  Verfahren: kodiere 'existiert eine Schaltung mit genau g Gattern,")
print("  die diese Wahrheitstabelle realisiert' als SAT-Instanz.")
print("  UNSAT = BEWEIS, dass keine Schaltung dieser Groesse existiert.")
print()
print("  Machbarkeitsgrenze in der Praxis (Stand der Technik):")
for g, status in [(4,"Sekunden"),(6,"Minuten"),(8,"Stunden"),
                  (10,"Tage bis Wochen"),(12,"jenseits des Machbaren"),
                  (49,"voellig ausgeschlossen")]:
    print(f"    g = {g:>2} Gatter: {status}")
print()
print("  -> Beweisbar waere hoechstens: 'keine Schaltung mit <= 10 Gattern'.")
print("     Das ist weit unter der Abzaehlschranke von 49 - also eine Aussage,")
print("     die wir ohnehin schon durch Abzaehlung fuer fast alle Funktionen")
print("     kennen. Der interessante Bereich 49..747 ist unerreichbar.")
print()
print("="*72)
print("4) WUERDE EIN SOLCHER BEWEIS ETWAS UEBER SHA-256 SAGEN?")
print("="*72)
print("  Nein - und der Grund ist praezise benennbar:")
print()
print("  a) DOMAENE: K1-1 ist eine Funktion von 16 Bit. SHA-256-Sicherheit")
print("     ist eine Aussage ueber 2^256 Eingaben. Eine Schranke fuer eine")
print("     16-Bit-Funktion sagt nichts ueber Urbildresistenz im 256-Bit-Raum.")
print()
print("  b) RICHTUNG: Schaltungsgroesse misst, wie teuer das BERECHNEN ist.")
print("     Kryptografische Sicherheit misst, wie teuer das INVERTIEREN ist.")
print("     Das sind verschiedene Groessen - eine kleine Schaltung kann")
print("     schwer invertierbar sein und umgekehrt.")
print()
print("  c) EINSCHRAENKUNG: K1-1 entsteht durch Fixieren von 240 der 256")
print("     Eingabebits. Genau diese Fixierung entfernt, was SHA-256")
print("     kryptografisch ausmacht. Aussagen ueber die Restriktion")
print("     uebertragen sich nicht auf die volle Funktion.")
print()
print("  d) RICHTUNG DER IMPLIKATION: selbst ein Beweis 'K1-1 braucht viele")
print("     Gatter' waere eine Aussage ueber EINE Instanz. Sicherheit")
print("     erfordert eine Aussage ueber ALLE Angriffe - das ist quantifiziert")
print("     genau andersherum.")
print()
print("="*72)
print("5) WAS FUER WEG 1 REALISTISCH BLEIBT")
print("="*72)
print("  Die Luecke 49..747 ist echt offen. Suchverfahren, die dort greifen:")
print()
print("  - Exakte SAT-Synthese fuer TEILFUNKTIONEN (z.B. nur 8 der 16 Bit)")
print("    -> liefert echte, kleine, beweisbar minimale Bausteine")
print("  - Resynthese des bestehenden 747-Graphen (Cut-Rewriting, wie ABC)")
print("    -> realistisch 20-40 % Reduktion, semantikerhaltend")
print("  - MDL-Suche mit sauberem Holdout statt reiner Trefferquote")
print("    -> vermeidet genau den Auswendiglern-Effekt")
print()
print("  Alle drei liefern kleinere Schaltungen. Keine davon liefert einen")
print("  Angriff auf SHA-256 - sie machen das Berechnen billiger,")
print("  nicht das Invertieren.")
